### ISSUE TITLE
Circle CI build failing dur to error: Warning: Task "mochaTest:src" failed. Use --force to continue.

### ISSUE THREAD

**Issue by rstellar** [OrgCurrent/webApp#85]
> > ```
> > at Object.task.registerMultiTask.thisTask (/home/ubuntu/webApp/node_modules/grunt/lib/grunt/task.js:264:15)
> > at Object.task.registerTask.thisTask.fn (/home/ubuntu/webApp/node_modules/grunt/lib/grunt/task.js:82:16)
> > at Object.Task.start._running (/home/ubuntu/webApp/node_modules/grunt/lib/util/task.js:301:30)
> > at Task.runTaskFn (/home/ubuntu/webApp/node_modules/grunt/lib/util/task.js:251:24)
> > at Task.<anonymous> (/home/ubuntu/webApp/node_modules/grunt/lib/util/task.js:300:12)
> > at Task.runTaskFn.context.async.async (/home/ubuntu/webApp/node_modules/grunt/lib/util/task.js:227:11)
> > at process.startup.processNextTick.process._tickCallback (node.js:244:9)
> > ```
> > 
> > Warning: Task "mochaTest:src" failed. Use --force to continue.

Aborted due to warnings.

Execution Time (2014-08-12 06:00:10 UTC)
mochaTest:src  482ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 99%
Total 489ms
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
((npm :test)) returned exit code 1

**Comment by rstellar** [comment]
@omkarv @vhalbwachs @marcoau Circle CI is failing. I think it has something to do with Crypto, but I am still investigating. 

Any idea why ?

**Comment by vhalbwachs** [comment]
Looks like the tests are failing, could be for a number of reasons. I commented them out, try again with the updates.

**Comment by rstellar** [comment]
Thanks!

::::::::Sent from my human A/D converter:::::::
